name: Setup pnpm and Node.js
description: Checkout, setup pnpm, setup Node.js, and install dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.7.1
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"

    - run: pnpm install --frozen-lockfile
      shell: bash